export interface Position { id: string; itemId: string; locationId: string; lotId?: string; quantityOnHand: number; quantityReserved: number; quantityDamaged: number; quantityQuarantined: number; quantityInTransit: number; availableQuantity: number; transferableQuantity: number; lastCountedAt?: string }
export interface Lot { id: string; itemId: string; lotNumber: string; supplierLot?: string; manufactureDate?: string; expiryDate?: string; bestBeforeDate?: string; storageRequirements?: string; status: string; notes?: string }
export interface TransferLine { id: string; itemId: string; itemName: string; assetInstanceId?: string; assetCode?: string; lotId?: string; requestedQuantity: number; pickedQuantity: number; receivedQuantity: number; discrepancyQuantity: number; discrepancyNotes?: string }
export interface Transfer { id: string; transferNumber: string; sourceLocationId: string; destinationLocationId: string; status: string; dispatchedAt?: string; receivedAt?: string; notes?: string; lines: TransferLine[] }
export interface CountLine { id: string; itemId: string; itemName: string; assetCode?: string; lotId?: string; locationId?: string; expectedQuantity?: number; countedQuantity?: number; recountedQuantity?: number; approvedQuantity?: number; varianceQuantity?: number; countedById?: string; notes?: string }
export interface Count { id: string; sessionNumber: string; locationId?: string; blindCount: boolean; status: string; notes?: string; approvedById?: string; lines: CountLine[] }
export interface Schedule { id: string; itemId: string; assetInstanceId?: string; assetCode?: string; maintenanceType: string; intervalType: string; intervalValue: number; nextDueAt?: string; nextDueValue?: number; warningWindow?: number; responsiblePersonId?: string; requiredChecklist?: string; checkoutBlocking: boolean; active: boolean }
export interface Repair { id: string; damageReportId: string; assetInstanceId?: string; status: string; repairOwnerId?: string; vendorId?: string; safetyImpact: boolean; partsAndCostNotes?: string; verificationResult?: string; notes?: string }
export interface Receipt { id: string; receiptNumber: string; purchaseOrderId: string; receivedAt: string; receivingLocationId: string; status: string; notes?: string; lines: { id: string; itemName: string; acceptedQuantity: number; damagedQuantity: number; rejectedQuantity: number; receivingNotes?: string }[] }
export interface VendorDocument { id: string; vendorId: string; purchaseOrderId?: string; goodsReceiptId?: string; documentType: string; originalFilename: string; objectStorageKey: string; documentDate?: string; referenceNumber?: string; totalAmountCents?: number; currency?: string; uploadedAt: string; retentionUntil?: string; notes?: string }
export interface OutboxEvent { id: string; eventType: string; aggregateType: string; aggregateId: string; status: string; attemptCount: number; lastError?: string; occurredAt: string }
export interface SyncAudit { id: string; operationType: string; syncStatus: string; conflictMessage?: string; createdAt: string; userId: string; commandId: string; retryCount: number }

export interface LotInput { itemId: string; lotNumber: string; supplierLot?: string | null; manufactureDate?: string | null; expiryDate?: string | null; bestBeforeDate?: string | null; storageRequirements?: string | null; status?: 'available' | 'hold' | 'recalled' | 'expired' | 'depleted'; notes?: string | null }
export interface TransferInput { transferNumber?: string | null; sourceLocationId: string; destinationLocationId: string; idempotencyKey: string; notes?: string | null; lines: { itemId: string; assetInstanceId?: string | null; lotId?: string | null; quantity: number }[] }
export interface TransferCommandInput { idempotencyKey: string; notes?: string | null }
export interface TransferReceiveInput extends TransferCommandInput { lines: { transferLineId: string; receivedQuantity: number; discrepancyQuantity: number; discrepancyNotes?: string | null }[] }
export type TransferCommands = { dispatch: TransferCommandInput; cancel: TransferCommandInput; receive: TransferReceiveInput };
export interface CountInput { sessionNumber?: string | null; warehouseId?: string | null; locationId?: string | null; category?: string | null; itemId?: string | null; blindCount: boolean; notes?: string | null }
export interface CountCommandInput { notes?: string | null }
export interface CountSubmissionInput extends CountCommandInput { lines: { lineId: string; quantity: number; notes?: string | null }[] }
export type CountCommands = { start: CountCommandInput; submit: CountSubmissionInput; recount: CountSubmissionInput; approve: CountCommandInput; post: CountCommandInput; cancel: CountCommandInput };
export interface ScheduleInput { itemId: string; assetInstanceId?: string | null; maintenanceType: 'dguv_v3' | 'generator_service' | 'battery_test' | 'chrono_fps'; intervalType: 'date' | 'operating_hours' | 'usage_count'; intervalValue: number; nextDueAt?: string | null; nextDueValue?: number | null; warningWindow?: number | null; responsiblePersonId?: string | null; requiredChecklist?: string | null; checkoutBlocking: boolean; active?: boolean }
export interface RepairInput { damageReportId: string; repairOwnerId?: string | null; vendorId?: string | null; partsAndCostNotes?: string | null; notes?: string | null; occurredAt?: string | null }
export type RepairStatus = 'reported' | 'triaged' | 'awaiting_repair' | 'in_repair' | 'repaired' | 'verified' | 'returned_to_service' | 'written_off';
export interface RepairTransitionInput { status: RepairStatus; amount?: number | null; repairOwnerId?: string | null; vendorId?: string | null; verificationResult?: string | null; notes?: string | null; idempotencyKey?: string | null; occurredAt?: string | null }
export interface ReceiptLineInput { purchaseOrderLineId: string; acceptedQuantity: number; damagedQuantity: number; rejectedQuantity: number; lotId?: string | null; assetCodes?: string[]; receivingNotes?: string | null }
export interface ReceiptInput { purchaseOrderId: string; receiptNumber?: string | null; receivingLocationId: string; receivedAt?: string | null; idempotencyKey: string; notes?: string | null; lines: ReceiptLineInput[] }
export interface VendorDocumentInput { vendorId: string; purchaseOrderId?: string | null; goodsReceiptId?: string | null; documentType: 'invoice' | 'delivery_note' | 'quote' | 'warranty' | 'certificate' | 'other'; documentDate?: string | null; referenceNumber?: string | null; totalAmountCents?: number | null; currency?: string | null; retentionUntil?: string | null; notes?: string | null }
