-- Commit-ordered revisions: row updates roll back with source writes.
CREATE TABLE IF NOT EXISTS source_revisions (name varchar(100) PRIMARY KEY, revision bigint NOT NULL DEFAULT 0, epoch uuid NOT NULL DEFAULT gen_random_uuid());
CREATE OR REPLACE FUNCTION advance_source_revision() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE touched bigint;
BEGIN
    EXECUTE format('UPDATE %I.source_revisions SET revision = revision + 1 WHERE name = $1', TG_TABLE_SCHEMA) USING TG_TABLE_NAME;
    GET DIAGNOSTICS touched = ROW_COUNT;
    IF touched = 0 THEN RAISE EXCEPTION 'Missing source revision for %', TG_TABLE_NAME; END IF;
    RETURN NULL;
END;
$$;
INSERT INTO source_revisions (name, revision) VALUES ('items', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON items FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('storage_locations', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON storage_locations FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('warehouses', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON warehouses FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('event_occurrences', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON event_occurrences FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('faction_orders', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON faction_orders FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('faction_order_lines', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON faction_order_lines FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('general_orders', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON general_orders FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('app_users', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON app_users FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('vendors', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON vendors FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('stock_reservations', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON stock_reservations FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('inventory_positions', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON inventory_positions FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('inventory_lots', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON inventory_lots FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('asset_instances', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON asset_instances FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('return_submissions', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON return_submissions FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('damage_reports', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON damage_reports FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('repair_cases', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON repair_cases FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('maintenance_schedules', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON maintenance_schedules FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('maintenance_records', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON maintenance_records FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('purchase_orders', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON purchase_orders FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('purchase_order_lines', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON purchase_order_lines FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('inventory_count_sessions', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON inventory_count_sessions FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('inventory_count_lines', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON inventory_count_lines FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('stock_transactions', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON stock_transactions FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('equipment_commitments', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON equipment_commitments FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('loan_arrangements', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON loan_arrangements FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('member_requests', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON member_requests FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
INSERT INTO source_revisions (name, revision) VALUES ('factions', 0) ON CONFLICT (name) DO NOTHING;
CREATE OR REPLACE TRIGGER source_revision AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON factions FOR EACH STATEMENT EXECUTE FUNCTION advance_source_revision();
